language: python
python:
- 3.4

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y python3-numpy python3-scipy

install:
- pip3 install pep8 pyflakes coverage
- pip3 install -r requirements.txt

script:
- pep8 --max-line-length=100 .
- nosetests --with-coverage

after_success:
- bash <(curl -s https://codecov.io/bash)

